# Rekord Box Tag Inference

In [6]:
# automatically reload imported modules before executing code

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
from nbutils import setup_path

setup_path()

In [8]:
from pyrekordbox import Rekordbox6Database
from pyrekordbox.db6 import tables

# Get table refs 
song_table = tables.DjmdContent
tag_table = tables.DjmdMyTag
song_tag_table = tables.DjmdSongMyTag

In [4]:
from utils import get_db_content

db = Rekordbox6Database()

raw_df = get_db_content(db)

In [9]:
raw_df.head(10)

shape: (10, 12)
┌───────────┬────────────┬────────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ ContentID ┆ FolderPath ┆ Title      ┆ ArtistID  ┆ … ┆ DateCreat ┆ Length ┆ MyTagName ┆ MyTagIDs  │
│ ---       ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ed        ┆ ---    ┆ s         ┆ ---       │
│ str       ┆ str        ┆ str        ┆ str       ┆   ┆ ---       ┆ i32    ┆ ---       ┆ list[str] │
│           ┆            ┆            ┆           ┆   ┆ str       ┆        ┆ list[str] ┆           │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 36085625  ┆ /Users/qui ┆ Surrender  ┆ 167366459 ┆ … ┆ 2021-12-2 ┆ 413    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆            ┆ 6         ┆   ┆ 6         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 18988943  ┆ /Users/qui ┆ I Want     ┆ 164279802 ┆ … ┆ 2021-12-2 ┆ 399    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆ Your Soul  ┆ 5         ┆   ┆ 6         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 118919255 ┆ /Users/qui ┆ Save Our   ┆ 250819919 ┆ … ┆ 2022-08-2 ┆ 304    ┆ ["80s",   ┆ ["1155275 │
│           ┆ ntenrossee ┆ Love       ┆ 4         ┆   ┆ 3         ┆        ┆ "Disco",  ┆ 430", "62 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ …         ┆ 609778",  │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ "Chill"]  ┆ … "…      │
│ 228400738 ┆ /Users/qui ┆ RENT4      ┆ 395318805 ┆ … ┆ 2021-07-1 ┆ 167    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆            ┆ 5         ┆   ┆ 7         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 217615930 ┆ /Users/qui ┆ Funky      ┆ 113748359 ┆ … ┆ 2018-10-1 ┆ 227    ┆ ["Beats", ┆ ["2053683 │
│           ┆ ntenrossee ┆ Child      ┆ 5         ┆   ┆ 1         ┆        ┆ "Hip-Hop" ┆ 127", "39 │
│           ┆ l/Music/Pi ┆ (1993)     ┆           ┆   ┆           ┆        ┆ , … "TAG  ┆ 17148722" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ YE…       ┆ , ……      │
│ 121941058 ┆ /Users/qui ┆ I Wanna Do ┆ 324903329 ┆ … ┆ 2018-10-1 ┆ 390    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆ The Do     ┆ 0         ┆   ┆ 1         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆ (Extended  ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆ Re…        ┆           ┆   ┆           ┆        ┆           ┆           │
│ 261795999 ┆ /Users/qui ┆ Days Like  ┆ 645442704 ┆ … ┆ 2018-10-1 ┆ 486    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆ This (DJ   ┆           ┆   ┆ 1         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆ Spinna     ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆ Remi…      ┆           ┆   ┆           ┆        ┆           ┆           │
│ 191218482 ┆ /Users/qui ┆ Dancer     ┆ 276731648 ┆ … ┆ 2019-01-1 ┆ 507    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆            ┆           ┆   ┆ 1         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 55055504  ┆ /Users/qui ┆ Untitled   ┆ 408133230 ┆ … ┆ 2018-10-1 ┆ 475    ┆ ["Burning ┆ ["1695483 │
│           ┆ ntenrossee ┆ 02         ┆ 6         ┆   ┆ 1         ┆        ┆ Man",     ┆ 33", "414 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ "Loungy", ┆ 4163695", │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ … "T…     ┆ … …       │
│ 166336208 ┆ /Users/qui ┆ Talkin     ┆ 167972932 ┆ … ┆ 2022-08-2 ┆ 416    ┆ ["House", ┆ ["2688783 │
│           ┆ ntenrossee ┆ Bout Life  ┆ 4         ┆   ┆ 3         ┆        ┆ "Disco",  ┆ 057", "62 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ … "Soul"] ┆ 609778",  │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆ … "…      │
└───────────┴────────────┴────────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

# Simple Tagging Algorithm: Artist Propagation

A simple technique for tagging:

1. look at tags of other songs from a given artist
2. If a tag exist on any song of that artist, apply that same tag to the other untagged songs. 

177 such tags can be applied.

In [15]:
import polars as pl

processed_df = (
    raw_df
    .with_columns((pl.col("MyTagNames").list.len() > 0) .alias("has_tags"))
)

processed_df.head()

shape: (5, 13)
┌───────────┬────────────┬────────────┬────────────┬───┬────────┬───────────┬───────────┬──────────┐
│ ContentID ┆ FolderPath ┆ Title      ┆ ArtistID   ┆ … ┆ Length ┆ MyTagName ┆ MyTagIDs  ┆ has_tags │
│ ---       ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---    ┆ s         ┆ ---       ┆ ---      │
│ str       ┆ str        ┆ str        ┆ str        ┆   ┆ i32    ┆ ---       ┆ list[str] ┆ bool     │
│           ┆            ┆            ┆            ┆   ┆        ┆ list[str] ┆           ┆          │
╞═══════════╪════════════╪════════════╪════════════╪═══╪════════╪═══════════╪═══════════╪══════════╡
│ 36085625  ┆ /Users/qui ┆ Surrender  ┆ 1673664596 ┆ … ┆ 413    ┆ []        ┆ []        ┆ false    │
│           ┆ ntenrossee ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│ 18988943  ┆ /Users/qui ┆ I Want     ┆ 1642798025 ┆ … ┆ 399    ┆ []        ┆ []        ┆ false    │
│           ┆ ntenrossee ┆ Your Soul  ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│ 118919255 ┆ /Users/qui ┆ Save Our   ┆ 2508199194 ┆ … ┆ 304    ┆ ["80s",   ┆ ["1155275 ┆ true     │
│           ┆ ntenrossee ┆ Love       ┆            ┆   ┆        ┆ "Disco",  ┆ 430", "62 ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆ …         ┆ 609778",  ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆ "Chill"]  ┆ … "…      ┆          │
│ 228400738 ┆ /Users/qui ┆ RENT4      ┆ 3953188055 ┆ … ┆ 167    ┆ []        ┆ []        ┆ false    │
│           ┆ ntenrossee ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│ 217615930 ┆ /Users/qui ┆ Funky      ┆ 1137483595 ┆ … ┆ 227    ┆ ["Beats", ┆ ["2053683 ┆ true     │
│           ┆ ntenrossee ┆ Child      ┆            ┆   ┆        ┆ "Hip-Hop" ┆ 127", "39 ┆          │
│           ┆ l/Music/Pi ┆ (1993)     ┆            ┆   ┆        ┆ , … "TAG  ┆ 17148722" ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆ YE…       ┆ , ……      ┆          │
└───────────┴────────────┴────────────┴────────────┴───┴────────┴───────────┴───────────┴──────────┘

In [24]:
artist_tag_stats = (
    processed_df
    .group_by("ArtistID", "ArtistName", "has_tags")
    .agg(pl.len().alias("count"))
    .pivot(values="count", index=["ArtistID", "ArtistName"], on="has_tags")
    .filter(
        pl.col("true").is_not_null() & pl.col("false").is_not_null()
    )
    .with_columns(
        total=pl.col("true") + pl.col("false")
    )
    .sort("total", descending=True)
)

artist_tag_stats

shape: (81, 5)
┌────────────┬───────────────────┬───────┬──────┬───────┐
│ ArtistID   ┆ ArtistName        ┆ false ┆ true ┆ total │
│ ---        ┆ ---               ┆ ---   ┆ ---  ┆ ---   │
│ str        ┆ str               ┆ u32   ┆ u32  ┆ u32   │
╞════════════╪═══════════════════╪═══════╪══════╪═══════╡
│ 2476807121 ┆ BICEP             ┆ 12    ┆ 3    ┆ 15    │
│ 1908354044 ┆ Daft Punk         ┆ 8     ┆ 2    ┆ 10    │
│ null       ┆ null              ┆ 8     ┆ 1    ┆ 9     │
│ 3307290350 ┆ LAKIM             ┆ 8     ┆ 1    ┆ 9     │
│ 2388580169 ┆ Mansur Brown      ┆ 5     ┆ 4    ┆ 9     │
│ …          ┆ …                 ┆ …     ┆ …    ┆ …     │
│ 2361723307 ┆ Les Yeux Orange   ┆ 1     ┆ 1    ┆ 2     │
│ 1803051969 ┆ Lio               ┆ 1     ┆ 1    ┆ 2     │
│ 4205567497 ┆ Ayla              ┆ 1     ┆ 1    ┆ 2     │
│ 3304314106 ┆ Kate Bush         ┆ 1     ┆ 1    ┆ 2     │
│ 2307674511 ┆ Against All Logic ┆ 1     ┆ 1    ┆ 2     │
└────────────┴───────────────────┴───────┴──────┴───────┘

In [26]:
artist_tag_stats['false'].sum()

177