# Tag EDA

Explore tags & their relationship with songs.

- How many songs per TAG 
- How many songs per TAG group 
- What are popular TAGs

In [6]:
# automatically reload imported modules before executing code

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
from nbutils import setup_path

setup_path()

In [8]:
from pyrekordbox import Rekordbox6Database
from pyrekordbox.db6 import tables

# Get table refs 
song_table = tables.DjmdContent
tag_table = tables.DjmdMyTag
song_tag_table = tables.DjmdSongMyTag

In [13]:
import polars as pl
from utils import get_db_content

db = Rekordbox6Database()

clean_songs_df = (
    get_db_content(db)
    .with_columns((pl.col("MyTagNames").list.len() > 0) .alias("has_tags"))
    .filter(
        (pl.col("BPM") > 0) & 
        (pl.col("ArtistName") != "rekordbox")
    ) # Filter sample packs
)

clean_songs_df.head(5)

shape: (5, 13)
┌───────────┬────────────┬────────────┬────────────┬───┬────────┬───────────┬───────────┬──────────┐
│ ContentID ┆ FolderPath ┆ Title      ┆ ArtistID   ┆ … ┆ Length ┆ MyTagName ┆ MyTagIDs  ┆ has_tags │
│ ---       ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---    ┆ s         ┆ ---       ┆ ---      │
│ str       ┆ str        ┆ str        ┆ str        ┆   ┆ i32    ┆ ---       ┆ list[str] ┆ bool     │
│           ┆            ┆            ┆            ┆   ┆        ┆ list[str] ┆           ┆          │
╞═══════════╪════════════╪════════════╪════════════╪═══╪════════╪═══════════╪═══════════╪══════════╡
│ 36085625  ┆ /Users/qui ┆ Surrender  ┆ 1673664596 ┆ … ┆ 413    ┆ []        ┆ []        ┆ false    │
│           ┆ ntenrossee ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│ 18988943  ┆ /Users/qui ┆ I Want     ┆ 1642798025 ┆ … ┆ 399    ┆ []        ┆ []        ┆ false    │
│           ┆ ntenrossee ┆ Your Soul  ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│ 118919255 ┆ /Users/qui ┆ Save Our   ┆ 2508199194 ┆ … ┆ 304    ┆ ["80s",   ┆ ["1155275 ┆ true     │
│           ┆ ntenrossee ┆ Love       ┆            ┆   ┆        ┆ "Disco",  ┆ 430", "62 ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆ …         ┆ 609778",  ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆ "Chill"]  ┆ … "…      ┆          │
│ 228400738 ┆ /Users/qui ┆ RENT4      ┆ 3953188055 ┆ … ┆ 167    ┆ []        ┆ []        ┆ false    │
│           ┆ ntenrossee ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ l/Music/Pi ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆           ┆           ┆          │
│ 217615930 ┆ /Users/qui ┆ Funky      ┆ 1137483595 ┆ … ┆ 227    ┆ ["Beats", ┆ ["2053683 ┆ true     │
│           ┆ ntenrossee ┆ Child      ┆            ┆   ┆        ┆ "Hip-Hop" ┆ 127", "39 ┆          │
│           ┆ l/Music/Pi ┆ (1993)     ┆            ┆   ┆        ┆ , … "TAG  ┆ 17148722" ┆          │
│           ┆ …          ┆            ┆            ┆   ┆        ┆ YE…       ┆ , ……      ┆          │
└───────────┴────────────┴────────────┴────────────┴───┴────────┴───────────┴───────────┴──────────┘

In [17]:
tag_schema = {
    "TagID": pl.Utf8, # read as string for joining later on
    "UUID": pl.Utf8,
    "TagGroup": pl.Utf8,
    "TagName": pl.Utf8,
}

clean_tags_df = (
    pl.read_csv("../data/unique_tags.csv", schema=tag_schema)
)

clean_tags_df

shape: (117, 4)
┌────────────┬─────────────────────────────────┬──────────┬────────────┐
│ TagID      ┆ UUID                            ┆ TagGroup ┆ TagName    │
│ ---        ┆ ---                             ┆ ---      ┆ ---        │
│ str        ┆ str                             ┆ str      ┆ str        │
╞════════════╪═════════════════════════════════╪══════════╪════════════╡
│ 1429694612 ┆ 3e973c3c-001b-4792-92f9-684d40… ┆ Genre    ┆ Techno     │
│ 2484825285 ┆ 22a59e2a-b3a6-470e-ad4b-92edda… ┆ Genre    ┆ Ambient    │
│ 3917148722 ┆ 7226a04c-8d3e-4f5a-b6be-acb6c5… ┆ Genre    ┆ Hip-Hop    │
│ 323305339  ┆ e8484566-7872-449c-bbb6-e9002b… ┆ Genre    ┆ Motown     │
│ 385085509  ┆ c9ab7b83-30a5-4797-b70c-7f18d7… ┆ Genre    ┆ Funk       │
│ …          ┆ …                               ┆ …        ┆ …          │
│ 4107364518 ┆ 6a67b8f3-7d9d-4742-b7a9-b5818f… ┆ Mood     ┆ Uptempo    │
│ 3210010963 ┆ 6869463b-5e4a-49f8-91f8-873b20… ┆ Mood     ┆ Guilty     │
│ 1018510990 ┆ 3d357a06-cb6c-428a-b41e-b16696… ┆ Mood     ┆ Spacy      │
│ 2383308136 ┆ 270d675a-740e-4c9e-879a-d2ac56… ┆ Mood     ┆ Industrial │
│ 4042435953 ┆ 887caf43-d27c-4688-8f02-7f9eae… ┆ Mood     ┆ Synths     │
└────────────┴─────────────────────────────────┴──────────┴────────────┘

# EDA
- Explode song per MyTagName to have a song-tag association
- Join this tag with their parent
- See the distributions

In [18]:
clean_eda_df = (
    clean_songs_df
    .explode(["MyTagNames", "MyTagIDs"]) # one tag per song
    .drop("MyTagNames")
    .rename({
        "MyTagIDs": "MyTagID"
    })
    .join(
        clean_tags_df,
        how="left",
        left_on="MyTagID",
        right_on="TagID"
    )
)

clean_eda_df.head(5)

shape: (5, 15)
┌───────────┬────────────┬────────────┬───────────┬───┬──────────┬───────────┬───────────┬─────────┐
│ ContentID ┆ FolderPath ┆ Title      ┆ ArtistID  ┆ … ┆ has_tags ┆ UUID      ┆ TagGroup  ┆ TagName │
│ ---       ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---       ┆ ---       ┆ ---     │
│ str       ┆ str        ┆ str        ┆ str       ┆   ┆ bool     ┆ str       ┆ str       ┆ str     │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═════════╡
│ 36085625  ┆ /Users/qui ┆ Surrender  ┆ 167366459 ┆ … ┆ false    ┆ null      ┆ null      ┆ null    │
│           ┆ ntenrossee ┆            ┆ 6         ┆   ┆          ┆           ┆           ┆         │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆          ┆           ┆           ┆         │
│           ┆ …          ┆            ┆           ┆   ┆          ┆           ┆           ┆         │
│ 18988943  ┆ /Users/qui ┆ I Want     ┆ 164279802 ┆ … ┆ false    ┆ null      ┆ null      ┆ null    │
│           ┆ ntenrossee ┆ Your Soul  ┆ 5         ┆   ┆          ┆           ┆           ┆         │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆          ┆           ┆           ┆         │
│           ┆ …          ┆            ┆           ┆   ┆          ┆           ┆           ┆         │
│ 118919255 ┆ /Users/qui ┆ Save Our   ┆ 250819919 ┆ … ┆ true     ┆ e6444280- ┆ Years &   ┆ 80s     │
│           ┆ ntenrossee ┆ Love       ┆ 4         ┆   ┆          ┆ 6cb5-4db9 ┆ Origin    ┆         │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆          ┆ -a791-167 ┆           ┆         │
│           ┆ …          ┆            ┆           ┆   ┆          ┆ f57…      ┆           ┆         │
│ 118919255 ┆ /Users/qui ┆ Save Our   ┆ 250819919 ┆ … ┆ true     ┆ 9c39933a- ┆ Genre     ┆ Disco   │
│           ┆ ntenrossee ┆ Love       ┆ 4         ┆   ┆          ┆ bd9a-45e9 ┆           ┆         │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆          ┆ -b710-e6c ┆           ┆         │
│           ┆ …          ┆            ┆           ┆   ┆          ┆ d2c…      ┆           ┆         │
│ 118919255 ┆ /Users/qui ┆ Save Our   ┆ 250819919 ┆ … ┆ true     ┆ c9ab7b83- ┆ Genre     ┆ Funk    │
│           ┆ ntenrossee ┆ Love       ┆ 4         ┆   ┆          ┆ 30a5-4797 ┆           ┆         │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆          ┆ -b70c-7f1 ┆           ┆         │
│           ┆ …          ┆            ┆           ┆   ┆          ┆ 8d7…      ┆           ┆         │
└───────────┴────────────┴────────────┴───────────┴───┴──────────┴───────────┴───────────┴─────────┘