# Rekord Box Tag Inference

Make sure to create a backup before running scripts. 
The backup dialog can be found under "File" > "Library" > "Backup Library".

In [7]:
# automatically reload imported modules before executing code

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
from nbutils import setup_path

setup_path()

In [1]:
from pyrekordbox import Rekordbox6Database
from pyrekordbox.db6 import tables

# Get table refs 
song_table = tables.DjmdContent
tag_table = tables.DjmdMyTag
song_tag_table = tables.DjmdSongMyTag

In [10]:
from utils import get_db_content

db = Rekordbox6Database()

raw_df = get_db_content(db)

In [11]:
raw_df.head(10)

shape: (10, 12)
┌───────────┬────────────┬────────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ ContentID ┆ FolderPath ┆ Title      ┆ ArtistID  ┆ … ┆ DateCreat ┆ Length ┆ MyTagName ┆ MyTagIDs  │
│ ---       ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ed        ┆ ---    ┆ s         ┆ ---       │
│ str       ┆ str        ┆ str        ┆ str       ┆   ┆ ---       ┆ i32    ┆ ---       ┆ list[str] │
│           ┆            ┆            ┆           ┆   ┆ str       ┆        ┆ list[str] ┆           │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 36085625  ┆ /Users/qui ┆ Surrender  ┆ 167366459 ┆ … ┆ 2021-12-2 ┆ 413    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆            ┆ 6         ┆   ┆ 6         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 18988943  ┆ /Users/qui ┆ I Want     ┆ 164279802 ┆ … ┆ 2021-12-2 ┆ 399    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆ Your Soul  ┆ 5         ┆   ┆ 6         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 118919255 ┆ /Users/qui ┆ Save Our   ┆ 250819919 ┆ … ┆ 2022-08-2 ┆ 304    ┆ ["80s",   ┆ ["1155275 │
│           ┆ ntenrossee ┆ Love       ┆ 4         ┆   ┆ 3         ┆        ┆ "Disco",  ┆ 430", "62 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ …         ┆ 609778",  │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ "Chill"]  ┆ … "…      │
│ 228400738 ┆ /Users/qui ┆ RENT4      ┆ 395318805 ┆ … ┆ 2021-07-1 ┆ 167    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆            ┆ 5         ┆   ┆ 7         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 217615930 ┆ /Users/qui ┆ Funky      ┆ 113748359 ┆ … ┆ 2018-10-1 ┆ 227    ┆ ["Beats", ┆ ["2053683 │
│           ┆ ntenrossee ┆ Child      ┆ 5         ┆   ┆ 1         ┆        ┆ "Hip-Hop" ┆ 127", "39 │
│           ┆ l/Music/Pi ┆ (1993)     ┆           ┆   ┆           ┆        ┆ , … "TAG  ┆ 17148722" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ YE…       ┆ , ……      │
│ 121941058 ┆ /Users/qui ┆ I Wanna Do ┆ 324903329 ┆ … ┆ 2018-10-1 ┆ 390    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆ The Do     ┆ 0         ┆   ┆ 1         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆ (Extended  ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆ Re…        ┆           ┆   ┆           ┆        ┆           ┆           │
│ 261795999 ┆ /Users/qui ┆ Days Like  ┆ 645442704 ┆ … ┆ 2018-10-1 ┆ 486    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆ This (DJ   ┆           ┆   ┆ 1         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆ Spinna     ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆ Remi…      ┆           ┆   ┆           ┆        ┆           ┆           │
│ 191218482 ┆ /Users/qui ┆ Dancer     ┆ 276731648 ┆ … ┆ 2019-01-1 ┆ 507    ┆ []        ┆ []        │
│           ┆ ntenrossee ┆            ┆           ┆   ┆ 1         ┆        ┆           ┆           │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆           │
│ 55055504  ┆ /Users/qui ┆ Untitled   ┆ 408133230 ┆ … ┆ 2018-10-1 ┆ 475    ┆ ["Burning ┆ ["1695483 │
│           ┆ ntenrossee ┆ 02         ┆ 6         ┆   ┆ 1         ┆        ┆ Man",     ┆ 33", "414 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ "Loungy", ┆ 4163695", │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ … "T…     ┆ … …       │
│ 166336208 ┆ /Users/qui ┆ Talkin     ┆ 167972932 ┆ … ┆ 2022-08-2 ┆ 416    ┆ ["House", ┆ ["2688783 │
│           ┆ ntenrossee ┆ Bout Life  ┆ 4         ┆   ┆ 3         ┆        ┆ "Disco",  ┆ 057", "62 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ … "Soul"] ┆ 609778",  │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆ … "…      │
└───────────┴────────────┴────────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

In [111]:
# Sample export 
sample_export_df = raw_df.filter(
    pl.col("MyTagNames").list.len() > 0
).head(100).write_json("data/content_sample.json")

# Get All Tags

In [106]:
raw_df.filter(
    (pl.col("MyTagNames").list.len() > 0) &
     (pl.col("MyTagNames").list.contains("TAG YEAR"))
    
)

shape: (11, 12)
┌───────────┬────────────┬────────────┬───────────┬───┬───────────┬────────┬───────────┬───────────┐
│ ContentID ┆ FolderPath ┆ Title      ┆ ArtistID  ┆ … ┆ DateCreat ┆ Length ┆ MyTagName ┆ MyTagIDs  │
│ ---       ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ed        ┆ ---    ┆ s         ┆ ---       │
│ str       ┆ str        ┆ str        ┆ str       ┆   ┆ ---       ┆ i32    ┆ ---       ┆ list[str] │
│           ┆            ┆            ┆           ┆   ┆ str       ┆        ┆ list[str] ┆           │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 34581633  ┆ /Users/qui ┆ Moon       ┆ 171002568 ┆ … ┆ 2022-08-2 ┆ 451    ┆ ["Garage" ┆ ["2478477 │
│           ┆ ntenrossee ┆ Landing    ┆ 4         ┆   ┆ 3         ┆        ┆ , "Future ┆ 436", "25 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ Bass", …  ┆ 18002351" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ "E…       ┆ , ……      │
│ 93269297  ┆ /Users/qui ┆ Time       ┆ 143702055 ┆ … ┆ 2021-07-1 ┆ 913    ┆ ["Burning ┆ ["1695483 │
│           ┆ ntenrossee ┆            ┆           ┆   ┆ 7         ┆        ┆ Man",     ┆ 33", "165 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ "Favs", … ┆ 295017",  │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ "Upl…     ┆ … "…      │
│ 249271134 ┆ /Users/qui ┆ Startrack  ┆ 516370755 ┆ … ┆ 2022-08-2 ┆ 346    ┆ ["Bass",  ┆ ["6818228 │
│           ┆ ntenrossee ┆            ┆           ┆   ┆ 3         ┆        ┆ "Future   ┆ 52", "251 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ Bass", …  ┆ 8002351", │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ "Upt…     ┆ … …       │
│ 15383749  ┆ /Users/qui ┆ Forget Me  ┆ 422187220 ┆ … ┆ 2021-07-1 ┆ 275    ┆ ["Classic ┆ ["2772879 │
│           ┆ ntenrossee ┆ Nots       ┆ 2         ┆   ┆ 7         ┆        ┆ s",       ┆ 171", "62 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ "Disco",  ┆ 609778",  │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ … "TAG Y… ┆ … "…      │
│ 126392049 ┆ /Users/qui ┆ Funky      ┆ null      ┆ … ┆ 2019-01-1 ┆ 367    ┆ ["Soul",  ┆ ["1488675 │
│           ┆ ntenrossee ┆ Disco      ┆           ┆   ┆ 5         ┆        ┆ "Live Ins ┆ 436", "14 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ trument   ┆ 40793859" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ Gems…     ┆ , ……      │
│ …         ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …      ┆ …         ┆ …         │
│ 198334285 ┆ /Users/qui ┆ Cape Coast ┆ 775340643 ┆ … ┆ 2023-04-2 ┆ 491    ┆ ["African ┆ ["2916771 │
│           ┆ ntenrossee ┆ (KM034)    ┆           ┆   ┆ 7         ┆        ┆ ", "TAG   ┆ 763", "38 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ YEAR", …  ┆ 2831235", │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ "Hou…     ┆ … …       │
│ 262561134 ┆ /Users/qui ┆ Conscious  ┆ 211350439 ┆ … ┆ 2023-08-1 ┆ 368    ┆ ["Soul",  ┆ ["1488675 │
│           ┆ ntenrossee ┆ Of My      ┆ 9         ┆   ┆ 2         ┆        ┆ "R&B", …  ┆ 436", "31 │
│           ┆ l/Music/Pi ┆ Conscience ┆           ┆   ┆           ┆        ┆ "Ladies"] ┆ 42461962" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆ , ……      │
│ 94042652  ┆ /Users/qui ┆ Teardrops  ┆ 211350439 ┆ … ┆ 2023-12-0 ┆ 228    ┆ ["Soul",  ┆ ["1488675 │
│           ┆ ntenrossee ┆            ┆ 9         ┆   ┆ 8         ┆        ┆ "R&B", …  ┆ 436", "31 │
│           ┆ l/Document ┆            ┆           ┆   ┆           ┆        ┆ "Danceflo ┆ 42461962" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ or"…      ┆ , ……      │
│ 104652117 ┆ /Users/qui ┆ Baby I'm   ┆ 211350439 ┆ … ┆ 2024-05-0 ┆ 337    ┆ ["Soul",  ┆ ["1488675 │
│           ┆ ntenrossee ┆ Scared of  ┆ 9         ┆   ┆ 4         ┆        ┆ "R&B", …  ┆ 436", "31 │
│           ┆ l/Document ┆ You        ┆           ┆   ┆           ┆        ┆ "Ladies"] ┆ 42461962" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆           ┆ , ……      │
│ 98250107  ┆ /Users/qui ┆ New For U  ┆ 419443825 ┆ … ┆ 2025-07-1 ┆ 312    ┆ ["House", ┆ ["2688783 │
│           ┆ ntenrossee ┆            ┆ 7         ┆   ┆ 0         ┆        ┆ "Soul", … ┆ 057", "14 │
│           ┆ l/Music/Pi ┆            ┆           ┆   ┆           ┆        ┆ "TAG      ┆ 88675436" │
│           ┆ …          ┆            ┆           ┆   ┆           ┆        ┆ YEAR"…    ┆ , ……      │
└───────────┴────────────┴────────────┴───────────┴───┴───────────┴────────┴───────────┴───────────┘

In [107]:
tag_cols = ["MyTagNames", "MyTagIDs"]

df_with_zipped_tags = (
        raw_df
        .select(tag_cols)
        .with_columns(
            pl.struct(tag_cols)
            .map_elements(
                lambda row: list(zip(*[row[c] for c in tag_cols])),
                return_dtype=pl.List(pl.Struct([pl.Field("name", pl.Utf8), pl.Field("id", pl.Utf8)]))
            )
        .alias("TagPairs")
    )
)

exploded_tags = (
    df_with_zipped_tags
    .select(pl.col("TagPairs"))
    .explode("TagPairs")
    .unnest("TagPairs")
)

# Get unique tags
unique_tags = (
    exploded_tags
    .unique()
    .sort("name")
    .filter(pl.col("name").is_not_null())
)

unique_tags

shape: (117, 2)
┌─────────────┬────────────┐
│ name        ┆ id         │
│ ---         ┆ ---        │
│ str         ┆ str        │
╞═════════════╪════════════╡
│ 00s         ┆ 200342229  │
│ 2010s       ┆ 1016231645 │
│ 2020s       ┆ 3992394433 │
│ 50s         ┆ 946468513  │
│ 60s         ┆ 3831639528 │
│ …           ┆ …          │
│ UK          ┆ 236289865  │
│ USA         ┆ 1443665513 │
│ Uplifting   ┆ 921280454  │
│ Uptempo     ┆ 4107364518 │
│ Yaught Rock ┆ 3857742348 │
└─────────────┴────────────┘

In [92]:
unique_tags.head(100)
unique_tags.write_csv("data/unique_tags.csv")