In [49]:
# automatically reload imported modules before executing code

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [72]:
from pyrekordbox import Rekordbox6Database
import polars as pl
from nbutils import setup_path

setup_path()
db = Rekordbox6Database()

pl.Config.set_tbl_rows(20)  # Show 100 row

[13:13:17] pyrekordbox.db6.database:WARNING  - Rekordbox is running!

polars.config.Config

In [78]:
from utils import get_base_dataset

base_df = get_base_dataset(db, min_tag_count=5)

Filtering tags with fewer than 5 occurrences:
============================================================

Genre:
  - Grime: 1 occurrence(s)
  - New Beat: 3 occurrence(s)
  - Dancehall: 3 occurrence(s)
  - Blues: 4 occurrence(s)
  - Gabber: 4 occurrence(s)

Mood:
  - Industrial: 1 occurrence(s)

============================================================
Total tags filtered: 6
============================================================

In [79]:
from sklearn.model_selection import train_test_split

# replace with ALL songs 
features_df = pl.read_parquet("../data/song_features.parquet")

Xy_df = (
    base_df
    .join(features_df, on=["song_id", "song_path"], how="left")
    .filter(pl.col("has_tags"))
    .drop([
        "song_path", 
        "song_title", 
        "artist_id",
        "artist_name",
        "genre_id",
        "genre_name",
        "date_created",
        "tag_id",
        "sample_rate",
        "has_tags",
        "harmonic_percussive_ratio",
        "percussive_strength",
        "tonnetz_mean_0",
        "tonnetz_mean_1",	
        "tonnetz_mean_2",	
        "tonnetz_mean_3",	
        "tonnetz_mean_4",
        "tonnetz_mean_5",
        "tonnetz_std_0",
        "tonnetz_std_1",
        "tonnetz_std_2",
        "tonnetz_std_3",
        "tonnetz_std_4",	
        "tonnetz_std_5"
    ])
    .filter(
        pl.col("energy_increase_ratio").is_not_null()
    )
)


Xy_mood_df = (
    Xy_df
    .filter(pl.col("tag_group") == "Mood")
    .drop("tag_group")
)

Xy_situation_df = (
    Xy_df
    .filter(pl.col("tag_group") == "Situation")
    .drop("tag_group")
)

Xy_genre_df = (
    Xy_df
    .filter(pl.col("tag_group") == "Genre")
    .drop("tag_group")
)

y_label = "tag_name"
test_size = 0.2

# Split mood data
X_mood = Xy_mood_df.drop(y_label)
y_mood = Xy_mood_df.select(y_label)
X_mood_train, X_mood_test, y_mood_train, y_mood_test = train_test_split(
    X_mood, y_mood, test_size=test_size, random_state=42, stratify=Xy_mood_df[y_label]
)

# Split situation data
X_situation = Xy_situation_df.drop(y_label)
y_situation = Xy_situation_df.select(y_label)
X_situation_train, X_situation_test, y_situation_train, y_situation_test = train_test_split(
    X_situation, y_situation, test_size=test_size, random_state=42, stratify=Xy_situation_df[y_label]
)

# Split genre data
X_genre = Xy_genre_df.drop(y_label)
y_genre = Xy_genre_df.select(y_label)
X_genre_train, X_genre_test, y_genre_train, y_genre_test = train_test_split(
    X_genre, y_genre, test_size=test_size, random_state=42, stratify=Xy_genre_df[y_label]
)

In [80]:
X_mood_train

shape: (1_736, 363)
┌───────────┬───────┬────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ song_id   ┆ bpm   ┆ length ┆ mel_spec_me ┆ … ┆ energy_sta ┆ energy_mid ┆ energy_end ┆ energy_inc │
│ ---       ┆ ---   ┆ ---    ┆ an_0        ┆   ┆ rt         ┆ dle        ┆ ---        ┆ rease_rati │
│ str       ┆ i32   ┆ i32    ┆ ---         ┆   ┆ ---        ┆ ---        ┆ f64        ┆ o          │
│           ┆       ┆        ┆ f64         ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│           ┆       ┆        ┆             ┆   ┆            ┆            ┆            ┆ f64        │
╞═══════════╪═══════╪════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 65069301  ┆ 11100 ┆ 371    ┆ -37.047718  ┆ … ┆ 0.138044   ┆ 0.202641   ┆ 0.151873   ┆ 1.100167   │
│ 204458084 ┆ 9540  ┆ 213    ┆ -24.755754  ┆ … ┆ 0.266494   ┆ 0.302025   ┆ 0.240726   ┆ 0.903302   │
│ 238045823 ┆ 12630 ┆ 353    ┆ -25.043629  ┆ … ┆ 0.194241   ┆ 0.26323    ┆ 0.233944   ┆ 1.204393   │
│ 71441805  ┆ 9750  ┆ 198    ┆ -33.232159  ┆ … ┆ 0.147312   ┆ 0.180405   ┆ 0.14817    ┆ 1.005816   │
│ 71892549  ┆ 12600 ┆ 380    ┆ -30.873152  ┆ … ┆ 0.263866   ┆ 0.216594   ┆ 0.204088   ┆ 0.773449   │
│ 157724688 ┆ 11200 ┆ 325    ┆ -49.252892  ┆ … ┆ 0.083454   ┆ 0.192988   ┆ 0.08279    ┆ 0.992028   │
│ 179764641 ┆ 9900  ┆ 158    ┆ -43.974846  ┆ … ┆ 0.160876   ┆ 0.178838   ┆ 0.179632   ┆ 1.116582   │
│ 178669006 ┆ 12100 ┆ 152    ┆ -31.607105  ┆ … ┆ 0.200744   ┆ 0.199217   ┆ 0.177449   ┆ 0.883955   │
│ 166725854 ┆ 12100 ┆ 355    ┆ -34.215809  ┆ … ┆ 0.195134   ┆ 0.208784   ┆ 0.136194   ┆ 0.697946   │
│ 65756518  ┆ 13300 ┆ 360    ┆ -28.00403   ┆ … ┆ 0.263111   ┆ 0.208234   ┆ 0.262545   ┆ 0.997845   │
│ …         ┆ …     ┆ …      ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 241002817 ┆ 12000 ┆ 333    ┆ -37.578716  ┆ … ┆ 0.15189    ┆ 0.248568   ┆ 0.18302    ┆ 1.204942   │
│ 168097679 ┆ 9150  ┆ 276    ┆ -35.908134  ┆ … ┆ 0.120491   ┆ 0.190676   ┆ 0.143303   ┆ 1.189318   │
│ 168886330 ┆ 11720 ┆ 351    ┆ -35.398575  ┆ … ┆ 0.101913   ┆ 0.125659   ┆ 0.143322   ┆ 1.406298   │
│ 83105824  ┆ 14000 ┆ 361    ┆ -26.702703  ┆ … ┆ 0.221042   ┆ 0.221212   ┆ 0.176362   ┆ 0.797866   │
│ 266628152 ┆ 12780 ┆ 598    ┆ -41.003269  ┆ … ┆ 0.081485   ┆ 0.133117   ┆ 0.08217    ┆ 1.008394   │
│ 79369571  ┆ 9750  ┆ 255    ┆ -34.591267  ┆ … ┆ 0.137553   ┆ 0.150882   ┆ 0.16368    ┆ 1.189938   │
│ 65069301  ┆ 11100 ┆ 371    ┆ -37.047718  ┆ … ┆ 0.138044   ┆ 0.202641   ┆ 0.151873   ┆ 1.100167   │
│ 176789993 ┆ 9170  ┆ 343    ┆ -21.51404   ┆ … ┆ 0.252775   ┆ 0.197072   ┆ 0.169812   ┆ 0.671788   │
│ 41517519  ┆ 12300 ┆ 715    ┆ -28.830725  ┆ … ┆ 0.138821   ┆ 0.207278   ┆ 0.222238   ┆ 1.600886   │
│ 142992519 ┆ 13070 ┆ 242    ┆ -37.117138  ┆ … ┆ 0.112587   ┆ 0.091535   ┆ 0.098879   ┆ 0.878233   │
└───────────┴───────┴────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [28]:
Xy_mood_df[[y_label, "song_id"]].group_by(y_label).count().filter(pl.col("count") < 5)[0:5]

/var/folders/2y/wcq7n_b14cqd36yz8rymh1540000gn/T/ipykernel_33433/3046250214.py:1: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  Xy_mood_df[[y_label, "song_id"]].group_by(y_label).count().filter(pl.col("count") < 5)[0:5]

shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ agg_tag                         ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Dancefloor, Good Vibes, Groovy… ┆ 4     │
│ Dancefloor, Groovy              ┆ 3     │
│ Chill, Good Vibes, Pretty, Upl… ┆ 3     │
│ Dancefloor, Good Vibes, Groovy… ┆ 2     │
│ Chill, Dancefloor, Good Vibes,… ┆ 3     │
└─────────────────────────────────┴───────┘

In [15]:
Xy_mood_df

shape: (181, 364)
┌───────────┬───────┬────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ song_id   ┆ bpm   ┆ length ┆ agg_tag     ┆ … ┆ energy_sta ┆ energy_mid ┆ energy_end ┆ energy_inc │
│ ---       ┆ ---   ┆ ---    ┆ ---         ┆   ┆ rt         ┆ dle        ┆ ---        ┆ rease_rati │
│ str       ┆ i32   ┆ i32    ┆ str         ┆   ┆ ---        ┆ ---        ┆ f64        ┆ o          │
│           ┆       ┆        ┆             ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│           ┆       ┆        ┆             ┆   ┆            ┆            ┆            ┆ f64        │
╞═══════════╪═══════╪════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 100050502 ┆ 11940 ┆ 260    ┆ Good Vibes, ┆ … ┆ 0.089394   ┆ 0.110782   ┆ 0.104654   ┆ 1.170696   │
│           ┆       ┆        ┆ Sunset,     ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Uplifting   ┆   ┆            ┆            ┆            ┆            │
│ 100643833 ┆ 12700 ┆ 364    ┆ Dancefloor, ┆ … ┆ 0.17499    ┆ 0.177955   ┆ 0.17005    ┆ 0.971767   │
│           ┆       ┆        ┆ Good Vibes, ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Groovy…     ┆   ┆            ┆            ┆            ┆            │
│ 10108318  ┆ 12700 ┆ 199    ┆ Dancefloor, ┆ … ┆ 0.054717   ┆ 0.061379   ┆ 0.045351   ┆ 0.828822   │
│           ┆       ┆        ┆ Good Vibes, ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Sunset…     ┆   ┆            ┆            ┆            ┆            │
│ …         ┆ …     ┆ …      ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 98250107  ┆ 12410 ┆ 312    ┆ Chill, Good ┆ … ┆ 0.180415   ┆ 0.156698   ┆ 0.128593   ┆ 0.712759   │
│           ┆       ┆        ┆ Vibes,      ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Groovy,     ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Sun…        ┆   ┆            ┆            ┆            ┆            │
│ 98932148  ┆ 11030 ┆ 134    ┆ Chill, Good ┆ … ┆ 0.162095   ┆ 0.158706   ┆ 0.163272   ┆ 1.007258   │
│           ┆       ┆        ┆ Vibes,      ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Pretty      ┆   ┆            ┆            ┆            ┆            │
└───────────┴───────┴────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [12]:
Xy_genre_df[0:5]

shape: (5, 378)
┌───────────┬───────┬────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ song_id   ┆ bpm   ┆ length ┆ agg_tag     ┆ … ┆ energy_sta ┆ energy_mid ┆ energy_end ┆ energy_inc │
│ ---       ┆ ---   ┆ ---    ┆ ---         ┆   ┆ rt         ┆ dle        ┆ ---        ┆ rease_rati │
│ str       ┆ i32   ┆ i32    ┆ str         ┆   ┆ ---        ┆ ---        ┆ f64        ┆ o          │
│           ┆       ┆        ┆             ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│           ┆       ┆        ┆             ┆   ┆            ┆            ┆            ┆ f64        │
╞═══════════╪═══════╪════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 101186312 ┆ 12500 ┆ 307    ┆ Disco,      ┆ … ┆ 0.125862   ┆ 0.225122   ┆ 0.261071   ┆ 2.074249   │
│           ┆       ┆        ┆ House, Soul ┆   ┆            ┆            ┆            ┆            │
│ 101533884 ┆ 11540 ┆ 248    ┆ Disco,      ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│           ┆       ┆        ┆ Funk,       ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Motown,     ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Soul        ┆   ┆            ┆            ┆            ┆            │
│ 104519868 ┆ 12030 ┆ 220    ┆ Disco,      ┆ … ┆ 0.127579   ┆ 0.14171    ┆ 0.106869   ┆ 0.837662   │
│           ┆       ┆        ┆ Funk,       ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Motown,     ┆   ┆            ┆            ┆            ┆            │
│           ┆       ┆        ┆ Soul        ┆   ┆            ┆            ┆            ┆            │
│ 104573928 ┆ 13000 ┆ 284    ┆ Pop         ┆ … ┆ 0.16467    ┆ 0.226503   ┆ 0.165084   ┆ 1.002503   │
│ 104652117 ┆ 10590 ┆ 337    ┆ R&B, Soul   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
└───────────┴───────┴────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘